---
    - name: just testing
      debug:
        msg: "User: {{ item.0.name }}, Key: {{ item.1 | dict2items }}"
      loop: "{{ user_list | subelements('git_config') }}"

# - name: Bash | Git Global Config
#   git_config:
#     name: "{{ item.1.key }}"
#     value: "{{ item.1.value }}"
#     scope: global
#   loop: "{{ [user_list, user_list_host, user_list_group] | flatten | subelements('git_config') }}"
#   become: yes
#   become_user: "{{ item.0.name }}"
